/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
/* @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  /*overviewSidebar: ['docOverview', {type: 'autogenerated', dirName: '.'}],*/

  // But you can create a sidebar manually
 
  documentationSidebar: [
    'DocOverview',
    {
      type: 'doc',
      label: 'Checklists and Training',
      id: 'CHECKLISTS_TRAINING/CHECKLISTS_TRAINING',
    },

    {
      type: 'doc',
      label: 'FROG Software',
      id: 'FROG_SOFTWARE/FROG_SOFTWARE',
    },
  
    {
      type: 'doc',
      label: 'Knowledgebase',
      id: 'KNOWLEDGEBASE/KNOWLEDGEBASE',
    },

    {
      type: 'doc',
      label: 'Search Documentation',
      id: 'SEARCH_DOCUMENTATION/SEARCH_DOCUMENTATION',
    },

    {
      type: 'doc',
      label: 'New Features',
      id: 'NEW_FEATURES/NEW_FEATURES',
    },
  ],
  
};

module.exports = sidebars;
